---
name: example
on:
  push:
jobs:
  development:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: '${{ secrets.AWS_REGION }}'
        role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-readonly'
    - run: aws sts get-caller-identity
  production:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: '${{ secrets.AWS_REGION }}'
        role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-administrator'
    - run: aws sts get-caller-identity
