---
name: example
on:
  push:
jobs:
  development:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: development
    steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: '${{ secrets.AWS_REGION }}'
        role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ASSUME_ROLE_NAME }}'
    - run: aws sts get-caller-identity
  production:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: production
    steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: '${{ secrets.AWS_REGION }}'
        role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ASSUME_ROLE_NAME }}'
    - run: aws sts get-caller-identity
